#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

# Check ESLint Standards
npx lint-staged ||
(
    echo '🔨❌ You have a problem in your code. Check linter 🔨❌
        Fix them and try commit again.';
)

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
