# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm modules
        id: cache-npmmodules
        uses: actions/cache@v2
        env:
          cache-name: cache-npm-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM Dependencies
        if: steps.cache-npmmodules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Install NPM Dependencies
        if: steps.cache-npmmodules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - run: npm run lint
      - run: npm run build
      - run: npm test
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Deploy Next.js app
        run: aws s3 sync ./out s3://portfolio-web725
